### PR TITLE
Fix #23553: When large amounts of data are loaded, shrinkwrap blocks ui when changing selection

### PR DESCRIPTION
**Pull request by tsmock**
For further details, see https://josm.openstreetmap.de/ticket/23553 .

### CODE REVIEW

**Review by ubipo — APPROVED** [review]
Thanks for the work, I appreciate the clean solution!

**Comment by ubipo** [comment]
I will be out of office for the coming week, so I won't be able to publish a new version

**Comment by tsmock** [comment]
That is fine.
If it helps (for the future), I've got a [GitHub action](https://github.com/JOSM/JOSMPluginAction) that will autopublish. The MapWithAI plugin can be used as an [example](https://github.com/JOSM/MapWithAI/blob/master/.github/workflows/ant.yml).

EDIT: The action uses the ant `build.xml` file. I don't remember if I tried to use gradle if there was no `build.xml` file.

**Comment by ubipo** [comment]
[Published as v1.0.6](https://github.com/ubipo/shrinkwrap/releases/tag/v1.0.6) and available in the plugin browser (update JOSM to 19017 or later)

**Pull request merged**
